default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["BUSINESS_PROJECT_DATABASE_USERNAME"] %>
  password: <%= ENV["BUSINESS_PROJECT_DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: business_project_development

test:
  <<: *default
  database: business_project_test


production:
  <<: *default
  database: business_project_production
  username: business_project
  password: <%= ENV["BUSINESS_PROJECT_DATABASE_PASSWORD"] %>
